"""Common helpers shared by the Trabalho 04 queue simulation scripts."""

import csv
import json
import math
import random
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


HIGH_PRIORITY = "alta"
LOW_PRIORITY = "baixa"
PRIORITY_VALUES = (HIGH_PRIORITY, LOW_PRIORITY)
DROP_REASON_LOW_FULL = "buffer_cheio_baixa_prioridade"
DROP_REASON_NO_LOW = "buffer_cheio_sem_baixa_para_substituir"
DROP_REASON_REPLACED = "substituido_por_alta_prioridade"
DROP_REASON_FCFS = "buffer_cheio_fcfs"
DROP_REASON_VALUES = (
    DROP_REASON_LOW_FULL,
    DROP_REASON_NO_LOW,
    DROP_REASON_REPLACED,
    DROP_REASON_FCFS,
)
CLASS_METRICS = (
    "arrivals",
    "accepted",
    "served",
    "dropped",
    "loss_probability",
    "throughput",
    "mean_waiting_time",
    "mean_system_time",
)
CONFIDENCE_Z = 1.96
REPLICATION_FIELDNAMES = (
    "queue_name",
    "queue_slug",
    "scenario_id",
    "replication",
    "seed",
    "lambda_rate",
    "mu_rate",
    "rho",
    "K",
    "N",
    "p_high",
    "servers",
    "service_distribution",
    "sim_time",
    "warmup_time",
    "measured_time",
    "arrivals_total",
    "arrivals_high",
    "arrivals_low",
    "accepted_total",
    "accepted_high",
    "accepted_low",
    "served_total",
    "served_high",
    "served_low",
    "dropped_total",
    "dropped_high",
    "dropped_low",
    "replaced_low",
    "loss_probability_total",
    "loss_probability_high",
    "loss_probability_low",
    "replacement_probability_low",
    "throughput_total",
    "throughput_high",
    "throughput_low",
    "server_utilization",
    "mean_system_occupancy",
    "mean_queue_occupancy",
    "mean_waiting_time",
    "mean_system_time",
    "mean_service_time",
    "p50_system_time",
    "p95_system_time",
    "p99_system_time",
    "mean_waiting_time_high",
    "mean_waiting_time_low",
    "mean_system_time_high",
    "mean_system_time_low",
    "little_law_error_abs",
    "little_law_error_rel",
    "mean_residence_time_admitted",
    "departed_admitted_total",
    "admitted_departure_rate",
    "little_law_error_admitted",
)
SUMMARY_FIELDNAMES = (
    "queue_name",
    "queue_slug",
    "scenario_id",
    "metric",
    "n",
    "mean",
    "std",
    "ci95_low",
    "ci95_high",
)
CLASS_SUMMARY_FIELDNAMES = (
    "queue_name",
    "queue_slug",
    "scenario_id",
    "priority",
    "metric",
    "n",
    "mean",
    "std",
    "ci95_low",
    "ci95_high",
)
OCCUPANCY_FIELDNAMES = (
    "queue_name",
    "queue_slug",
    "scenario_id",
    "replication",
    "state",
    "time_in_state",
    "probability",
)
TIME_SERIES_FIELDNAMES = (
    "queue_name",
    "queue_slug",
    "scenario_id",
    "replication",
    "time",
    "num_in_system",
    "num_in_queue",
    "busy_servers",
)


@dataclass
class Packet:
    """Represent one packet tracked throughout the event-driven simulation.

    Args:
        id (int): Unique packet identifier generated by the simulator.
        priority (str): Packet class. Accepted values are `"alta"` for the
            high-priority class and `"baixa"` for the low-priority class.
        arrival_time (float): Simulation clock time in seconds when the packet
            entered the system attempt flow.
        service_start_time (float | None): Time in seconds when service began.
            Use `None` before service starts.
        departure_time (float | None): Time in seconds when service completed.
            Use `None` until the packet leaves by completion.
        service_time (float | None): Service duration in seconds assigned when
            the packet starts service. Use `None` before assignment.
        drop_time (float | None): Time in seconds when the packet was dropped.
            Use `None` for packets that were not discarded.
        drop_reason (str | None): Drop reason slug. Accepted values are
            `"buffer_cheio_baixa_prioridade"`,
            `"buffer_cheio_sem_baixa_para_substituir"`,
            `"substituido_por_alta_prioridade"`, and `"buffer_cheio_fcfs"`.
            Use `None` when the packet was not dropped.
        was_accepted (bool): `True` when the packet entered service or a queue.
        was_dropped (bool): `True` when the packet was discarded instead of
            being accepted.
        was_replaced (bool): `True` only for low-priority packets removed from
            the buffer by a later high-priority arrival.

    Returns:
        Packet: Dataclass instance with mutable simulation fields.

    Raises:
        ValueError: If `priority` or `drop_reason` is outside the supported
            values.

    Examples:
        >>> packet = Packet(1, "alta", 0.1, None, None, None, None, None, False, False, False)
        >>> packet.priority
        'alta'
    """

    id: int
    priority: str
    arrival_time: float
    service_start_time: float | None
    departure_time: float | None
    service_time: float | None
    drop_time: float | None
    drop_reason: str | None
    was_accepted: bool
    was_dropped: bool
    was_replaced: bool

    def __post_init__(self):
        """Validate packet categorical fields immediately after construction.

        Args:
            None: Dataclass validation uses the already assigned instance
                attributes.

        Returns:
            None: The method mutates nothing when validation succeeds.

        Raises:
            ValueError: If `priority` or `drop_reason` is invalid.
        """
        if self.priority not in PRIORITY_VALUES:
            raise ValueError(f"Unsupported priority: {self.priority}")
        if self.drop_reason is not None and self.drop_reason not in DROP_REASON_VALUES:
            raise ValueError(f"Unsupported drop reason: {self.drop_reason}")


def ensure_dir(path):
    """Create a directory path if needed and return it as `Path`.

    Args:
        path (str | Path): Target directory path. If the directory already
            exists, this function leaves it unchanged. If parents are missing,
            they are created as well.

    Returns:
        Path: Resolved directory path.

    Raises:
        OSError: If the directory cannot be created.
    """
    path_obj = Path(path).resolve()
    path_obj.mkdir(parents=True, exist_ok=True)
    return path_obj


def write_json(path, data):
    """Write JSON data to disk with a stable human-readable format.

    Args:
        path (str | Path): Output file path. Parent directories are created if
            necessary. Existing files are replaced.
        data (object): JSON-serializable Python value to persist.

    Returns:
        Path: Resolved output file path.

    Raises:
        OSError: If the file cannot be written.
        TypeError: If `data` is not JSON serializable.
    """
    output_path = Path(path).resolve()
    ensure_dir(output_path.parent)
    with open(output_path, "w", encoding="utf-8") as file_obj:
        json.dump(data, file_obj, indent=2, ensure_ascii=False)
        file_obj.write("\n")
    return output_path


def write_dicts_csv(path, rows, fieldnames):
    """Write dictionary rows to a CSV file using a fixed column order.

    Args:
        path (str | Path): Output CSV path. Parent directories are created if
            necessary. Existing files are replaced.
        rows (list[dict]): Sequence of row dictionaries aligned to
            `fieldnames`. Missing keys are written as empty fields.
        fieldnames (list[str] | tuple[str, ...]): Ordered column names used for
            the header and row serialization.

    Returns:
        Path: Resolved CSV path.

    Raises:
        OSError: If the file cannot be written.
        csv.Error: If the CSV writer fails.
    """
    output_path = Path(path).resolve()
    ensure_dir(output_path.parent)
    with open(output_path, "w", encoding="utf-8", newline="") as file_obj:
        writer = csv.DictWriter(file_obj, fieldnames=list(fieldnames))
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    return output_path


def exponential_time(rate, rng):
    """Draw an exponential random variate for one positive rate parameter.

    Args:
        rate (float): Event rate in events per second. Larger values produce
            smaller expected intervals. The value must be strictly positive.
        rng (random.Random): Random number generator that provides
            `expovariate(rate)`.

    Returns:
        float: Sampled interval in seconds.

    Raises:
        ValueError: If `rate` is not strictly positive.

    Examples:
        >>> import random
        >>> sample = exponential_time(2.0, random.Random(1))
        >>> sample > 0.0
        True
    """
    if rate <= 0.0:
        raise ValueError("rate must be strictly positive.")
    return rng.expovariate(rate)


def generate_priority(p_high, rng):
    """Generate a packet priority from a Bernoulli class-selection rule.

    Args:
        p_high (float): Probability of generating a high-priority packet.
            `0.0` always returns `"baixa"`. `1.0` always returns `"alta"`.
            Intermediate values split arrivals proportionally. The value must
            stay within `[0.0, 1.0]`.
        rng (random.Random): Random number generator that provides `random()`.

    Returns:
        str: `"alta"` when the Bernoulli draw falls below `p_high`,
            otherwise `"baixa"`.

    Raises:
        ValueError: If `p_high` is outside `[0.0, 1.0]`.

    Examples:
        >>> import random
        >>> generate_priority(1.0, random.Random(1))
        'alta'
    """
    if p_high < 0.0 or p_high > 1.0:
        raise ValueError("p_high must be within [0.0, 1.0].")
    if rng.random() < p_high:
        return HIGH_PRIORITY
    return LOW_PRIORITY


def generate_service_time(mu, service_distribution, rng):
    """Generate one service time using the requested service distribution.

    Args:
        mu (float): Mean service rate in packets per second. For all supported
            modes the expected service time is `1 / mu`, so larger `mu` values
            reduce average service duration. The value must be strictly
            positive.
        service_distribution (str): Service-time mode selector.
            `"exponential"` uses `rng.expovariate(mu)`, which has the highest
            variance among the supported options and models M/M/* systems.
            `"deterministic"` returns exactly `1.0 / mu`, which removes
            service-time randomness and produces the lowest variance.
            `"uniform"` samples from `[0.0, 2.0 / mu]`, preserving the same
            mean while adding bounded variability lower than the exponential
            case.
        rng (random.Random): Random number generator used by the stochastic
            modes. The deterministic mode does not consume randomness.

    Returns:
        float: Service time in seconds.

    Raises:
        ValueError: If `mu` is not strictly positive or if
            `service_distribution` is unsupported.

    Examples:
        >>> import random
        >>> generate_service_time(4.0, "deterministic", random.Random(1))
        0.25
    """
    if mu <= 0.0:
        raise ValueError("mu must be strictly positive.")
    if service_distribution == "exponential":
        return rng.expovariate(mu)
    if service_distribution == "deterministic":
        return 1.0 / mu
    if service_distribution == "uniform":
        return rng.uniform(0.0, 2.0 / mu)
    raise ValueError(f"Unsupported service distribution: {service_distribution}")


def safe_divide(numerator, denominator):
    """Divide two numbers while returning `0.0` for a zero denominator.

    Args:
        numerator (float): Value in the division numerator.
        denominator (float): Value in the division denominator. If this value
            is zero, the function returns `0.0` to keep summary metrics defined
            for empty class counts, exactly as required by the project outputs.

    Returns:
        float: `numerator / denominator` when `denominator != 0`, otherwise
            `0.0`.

    Raises:
        None: Zero-denominator handling is part of the required contract.
    """
    if denominator == 0:
        return 0.0
    return numerator / denominator


def mean(values):
    """Compute the arithmetic mean of a numeric sequence.

    Args:
        values (list[float]): Numeric values to average. The sequence must be
            non-empty.

    Returns:
        float: Arithmetic mean.

    Raises:
        ValueError: If `values` is empty.
    """
    if not values:
        raise ValueError("values must not be empty.")
    return sum(values) / len(values)


def sample_std(values):
    """Compute the sample standard deviation of a numeric sequence.

    Args:
        values (list[float]): Numeric values to summarize. For a single value,
            the function returns `0.0` because there is no replication
            variability to estimate.

    Returns:
        float: Sample standard deviation with Bessel correction.

    Raises:
        ValueError: If `values` is empty.
    """
    if not values:
        raise ValueError("values must not be empty.")
    if len(values) == 1:
        return 0.0
    avg = mean(values)
    variance = sum((value - avg) ** 2 for value in values) / (len(values) - 1)
    return math.sqrt(variance)


def percentile(values, q):
    """Compute a linear-interpolated percentile for one numeric sample.

    Args:
        values (list[float]): Numeric values to summarize. The sequence must be
            non-empty.
        q (float): Percentile in `[0.0, 100.0]`. `0.0` returns the minimum and
            `100.0` returns the maximum.

    Returns:
        float: Percentile estimate using linear interpolation between adjacent
            order statistics.

    Raises:
        ValueError: If `values` is empty or if `q` is outside `[0.0, 100.0]`.
    """
    if not values:
        raise ValueError("values must not be empty.")
    if q < 0.0 or q > 100.0:
        raise ValueError("q must be within [0.0, 100.0].")
    sorted_values = sorted(values)
    if len(sorted_values) == 1:
        return sorted_values[0]
    position = (len(sorted_values) - 1) * (q / 100.0)
    lower_index = int(math.floor(position))
    upper_index = int(math.ceil(position))
    if lower_index == upper_index:
        return sorted_values[lower_index]
    lower_value = sorted_values[lower_index]
    upper_value = sorted_values[upper_index]
    weight = position - lower_index
    return lower_value + ((upper_value - lower_value) * weight)


def confidence_interval_95(values):
    """Compute a normal-approximation 95% confidence interval for the mean.

    Args:
        values (list[float]): Replication values whose sample mean is being
            summarized. The sequence must be non-empty. A single value produces
            a degenerate interval with identical endpoints.

    Returns:
        tuple[float, float]: Lower and upper bounds of the 95% interval.

    Raises:
        ValueError: If `values` is empty.
    """
    if not values:
        raise ValueError("values must not be empty.")
    avg = mean(values)
    if len(values) == 1:
        return avg, avg
    half_width = CONFIDENCE_Z * sample_std(values) / math.sqrt(len(values))
    return avg - half_width, avg + half_width


def summarize_replications(replication_rows, metric_names):
    """Aggregate replication rows into the long summary format required.

    Args:
        replication_rows (list[dict]): Replication-level result rows. Every row
            must contain `queue_name`, `queue_slug`, `scenario_id`, and each
            requested metric key.
        metric_names (list[str] | tuple[str, ...]): Numeric metric columns to
            summarize across replications for each scenario.

    Returns:
        list[dict]: Long-format summary rows with fields
            `queue_name`, `queue_slug`, `scenario_id`, `metric`, `n`, `mean`,
            `std`, `ci95_low`, and `ci95_high`.

    Raises:
        ValueError: If `replication_rows` is empty.
        KeyError: If a required key is missing from a replication row.
    """
    if not replication_rows:
        raise ValueError("replication_rows must not be empty.")
    grouped_rows = defaultdict(list)
    for row in replication_rows:
        grouped_rows[row["scenario_id"]].append(row)

    summary_rows = []
    for scenario_id, scenario_rows in grouped_rows.items():
        queue_name = scenario_rows[0]["queue_name"]
        queue_slug = scenario_rows[0]["queue_slug"]
        for metric_name in metric_names:
            values = [float(row[metric_name]) for row in scenario_rows]
            ci95_low, ci95_high = confidence_interval_95(values)
            summary_rows.append(
                {
                    "queue_name": queue_name,
                    "queue_slug": queue_slug,
                    "scenario_id": scenario_id,
                    "metric": metric_name,
                    "n": len(values),
                    "mean": mean(values),
                    "std": sample_std(values),
                    "ci95_low": ci95_low,
                    "ci95_high": ci95_high,
                }
            )
    return summary_rows


def collect_class_summary(replication_rows):
    """Aggregate per-priority replication metrics into the required long form.

    Args:
        replication_rows (list[dict]): Replication-level result rows containing
            the class-specific metric columns such as `arrivals_high` and
            `mean_waiting_time_low`.

    Returns:
        list[dict]: Long-format rows with fields `queue_name`, `queue_slug`,
            `scenario_id`, `priority`, `metric`, `n`, `mean`, `std`,
            `ci95_low`, and `ci95_high`.

    Raises:
        ValueError: If `replication_rows` is empty.
        KeyError: If any required class metric column is missing.
    """
    if not replication_rows:
        raise ValueError("replication_rows must not be empty.")

    suffix_map = {"alta": "high", "baixa": "low"}
    summary_rows = []
    grouped_rows = defaultdict(list)
    for row in replication_rows:
        grouped_rows[row["scenario_id"]].append(row)

    for scenario_id, scenario_rows in grouped_rows.items():
        queue_name = scenario_rows[0]["queue_name"]
        queue_slug = scenario_rows[0]["queue_slug"]
        for priority_name, suffix in suffix_map.items():
            for metric_name in CLASS_METRICS:
                key = f"{metric_name}_{suffix}"
                values = [float(row[key]) for row in scenario_rows]
                ci95_low, ci95_high = confidence_interval_95(values)
                summary_rows.append(
                    {
                        "queue_name": queue_name,
                        "queue_slug": queue_slug,
                        "scenario_id": scenario_id,
                        "priority": priority_name,
                        "metric": metric_name,
                        "n": len(values),
                        "mean": mean(values),
                        "std": sample_std(values),
                        "ci95_low": ci95_low,
                        "ci95_high": ci95_high,
                    }
                )
    return summary_rows


def schedule_event(event_heap, time, event_counter, event_type, packet_id=None, server_id=None):
    """Push one event onto the heap and return the next sequence counter.

    Args:
        event_heap (list[tuple]): Heap-compatible list that stores events as
            `(time, event_counter, event_type, packet_id, server_id)`.
        time (float): Event timestamp in seconds.
        event_counter (int): Monotonic sequence number used to break ties for
            simultaneous events while preserving deterministic ordering.
        event_type (str): Event label. The project uses `"arrival"` and
            `"departure"`.
        packet_id (int | None): Packet identifier carried by the event. Arrival
            events may use `None` if the handler creates the packet on demand,
            while departure events usually point to the packet in service.
        server_id (int | None): Server identifier. Single-server scripts can
            leave this as `None`; the M/M/m script uses integer server indices.

    Returns:
        int: `event_counter + 1`, ready for the next scheduled event.

    Raises:
        None: Heap insertion itself does not validate event semantics.
    """
    import heapq

    heapq.heappush(event_heap, (time, event_counter, event_type, packet_id, server_id))
    return event_counter + 1


def update_area_metrics(
    *,
    last_time,
    current_time,
    warmup_time,
    sim_time,
    num_in_system,
    num_in_queue,
    busy_servers,
    occupancy_state_times,
    system_occupancy_area,
    queue_occupancy_area,
    busy_server_area,
):
    """Accumulate time-integrated occupancy metrics over the measured window.

    Args:
        last_time (float): Start of the interval being accumulated.
        current_time (float): End of the interval being accumulated.
        warmup_time (float): Statistics start time in seconds. Intervals before
            this point are ignored to enforce warm-up removal.
        sim_time (float): Statistics stop time in seconds. Intervals after this
            point are clipped because the project measures only up to
            `SIM_TIME`.
        num_in_system (int): Number of packets in the full system during the
            interval, including service and waiting.
        num_in_queue (int): Number of waiting packets during the interval.
        busy_servers (int): Number of servers busy during the interval. In
            single-server models this is `0` or `1`; in M/M/m it ranges from
            `0` to `m`.
        occupancy_state_times (dict[int, float]): Mutable mapping from system
            occupancy state to accumulated measured time.
        system_occupancy_area (float): Previous integral of `num_in_system`
            over measured time.
        queue_occupancy_area (float): Previous integral of `num_in_queue` over
            measured time.
        busy_server_area (float): Previous integral of `busy_servers` over
            measured time.

    Returns:
        tuple[float, float, float]: Updated
            `(system_occupancy_area, queue_occupancy_area, busy_server_area)`.

    Raises:
        ValueError: If `current_time < last_time`.
    """
    if current_time < last_time:
        raise ValueError("current_time must be greater than or equal to last_time.")

    measured_start = max(last_time, warmup_time)
    measured_end = min(current_time, sim_time)
    if measured_end <= measured_start:
        return system_occupancy_area, queue_occupancy_area, busy_server_area

    delta_time = measured_end - measured_start

    # State-time accumulation is the source for occupancy state probabilities,
    # so it must use the same clipped interval as the area metrics.
    occupancy_state_times[num_in_system] += delta_time
    system_occupancy_area += num_in_system * delta_time
    queue_occupancy_area += num_in_queue * delta_time
    busy_server_area += busy_servers * delta_time
    return system_occupancy_area, queue_occupancy_area, busy_server_area


def compute_little_law_error(mean_system_occupancy, throughput_total, mean_system_time):
    """Compute absolute and relative Little's Law consistency errors.

    Args:
        mean_system_occupancy (float): Mean number of packets in the system.
        throughput_total (float): Mean completed packets per second.
        mean_system_time (float): Mean packet time in system in seconds.

    Returns:
        tuple[float, float]: `(absolute_error, relative_error)` where the
            relative value is measured against `mean_system_occupancy` and uses
            `0.0` when the occupancy baseline is zero.

    Raises:
        None: Zero baseline is handled by the project-required safe division.
    """
    absolute_error = abs(mean_system_occupancy - (throughput_total * mean_system_time))
    relative_error = safe_divide(absolute_error, mean_system_occupancy)
    return absolute_error, relative_error


def build_admitted_little_metrics(
    mean_system_occupancy,
    measured_time,
    served_total,
    replaced_low,
    served_system_times,
    replaced_residence_times,
):
    """Compute admitted-packet residence metrics for Little's Law checks.

    Args:
        mean_system_occupancy (float): Mean number of packets in the system
            over the measured interval.
        measured_time (float): Duration in seconds of the measured interval.
            Larger values reduce the departure-rate estimate for fixed counts.
            The value must be non-negative.
        served_total (int): Number of served packets included in the measured
            arrival cohort.
        replaced_low (int): Number of low-priority packets from the measured
            arrival cohort that were later replaced while waiting.
        served_system_times (list[float]): Residence times in seconds for the
            served packets in the measured arrival cohort.
        replaced_residence_times (list[float]): Residence times in seconds for
            the replaced packets in the measured arrival cohort. Use an empty
            list for queue models without replacement.

    Returns:
        dict[str, float | int]: Dictionary with
            `mean_residence_time_admitted`, `departed_admitted_total`,
            `admitted_departure_rate`, and `little_law_error_admitted`.

    Raises:
        ValueError: If `measured_time` is negative.

    Examples:
        >>> build_admitted_little_metrics(4.0, 10.0, 30, 10, [1.0, 2.0], [3.0, 4.0])["departed_admitted_total"]
        40
    """
    if measured_time < 0.0:
        raise ValueError("measured_time must be non-negative.")

    residence_times = list(served_system_times) + list(replaced_residence_times)
    departed_admitted_total = int(served_total + replaced_low)
    mean_residence_time_admitted = mean(residence_times) if residence_times else 0.0
    admitted_departure_rate = safe_divide(departed_admitted_total, measured_time)
    little_law_error_admitted = abs(
        mean_system_occupancy - (admitted_departure_rate * mean_residence_time_admitted)
    )
    return {
        "mean_residence_time_admitted": mean_residence_time_admitted,
        "departed_admitted_total": departed_admitted_total,
        "admitted_departure_rate": admitted_departure_rate,
        "little_law_error_admitted": little_law_error_admitted,
    }
